#!/bin/sh

set -e

PARENT_PATH=$(dirname $(realpath $0))

echo "Linking .tmux.conf..."
ln -sf "$PARENT_PATH/tmux/.tmux.conf" "$HOME"

echo "Writing .vimrc..."

echo '" WARNING This .vimrc file was autogenerated.' > ~/.vimrc
echo "" >> ~/.vimrc
echo "source $PARENT_PATH/vimrcs/basic.vim" >> ~/.vimrc
echo "source $PARENT_PATH/vimrcs/fzf.vim" >> ~/.vimrc
echo "source $PARENT_PATH/vimrcs/coc.vim" >> ~/.vimrc
echo "" >> ~/.vimrc

echo "Done."

