#!/bin/sh

set -e

PARENT_PATH=$(dirname $(realpath $0))

echo "Linking .tmux.conf..."
ln -sf "$PARENT_PATH/tmux/.tmux.conf" "$HOME"

echo "Linking zsh configuration..."
ln -sf $PARENT_PATH/zsh/.zshrc $HOME
ln -sf $PARENT_PATH/zsh/.p10k.zsh $HOME

echo "Wriing .vimrc..."
echo '" WARNING This .vimrc file was autogenerated.' > ~/.vimrc
echo "" >> ~/.vimrc
echo "source $PARENT_PATH/vimrcs/basic.vim" >> ~/.vimrc
echo "source $PARENT_PATH/vimrcs/fzf.vim" >> ~/.vimrc
echo "source $PARENT_PATH/vimrcs/coc.vim" >> ~/.vimrc
echo "" >> ~/.vimrc

echo "Writing init.vim..."
mkdir -p $HOME/.config/
ln -sf $PARENT_PATH/.config/nvim $HOME/.config/

echo "Done."

